config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
 resources :rooms, except: [:edit] do
  member do
    get 'listing'
    get 'pricing'
    get 'description'
    get 'amenities'
    get 'photo_upload'
    get 'location'
    get 'preload'
    get 'preview'
  end

  resources :photos, only: [:create, :destroy]
  resources :reservations, only: [:create]
  resources :calendars
 end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => 'reservations#approve'
      post '/decline' => 'reservations#decline'
    end
  end

    get '/host_calendar' => "calendars#host"

    get '/notification_settings' => 'settings#edit'
    post '/notification_settings' => 'settings#update'
end

app/views/shared/_devisemsg.html.erb
<% unless resource.errors.empty?%>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |value| %>
        
            toastr.error('<%= value %>')
        <% end  %>
    </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty?%>
    <script type="text/javascript">
        <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
            toastr['<%= type %>']('<%= value %>')
        <% end  %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
<%# perhaps nav_bar is only for users pages. not for room show page?  %>

   <nav class="navbar navbar-default navbar-static-top" style ="margin-bottom: 0px">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to "Spanish Holiday Home", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">



<%# remove this section as I do not want guests to become hosts, create accounts or sign in %>

          <%# <li>
            <button class="btn btn-form btn-small">
            <%= link_to "Become a host", new_room_path, style: "color: white; text-decoration: none;" %>
        <%#  </button> %>
          <%#</li> %>
          <% if (!user_signed_in?) %>
            <li><%= link_to "HOST Login", new_user_session_path %>    </li>
           <li><%= link_to "HOST Sign Up", new_user_registration_path %> </li>
        <% else %>


      <%#      <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
              role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar_small"%>   <%#  &nbsp;
              <%= current_user.fullname %>   <%#  <span class="caret"></span>
              </a>
    <%# end of section to remove %>

              
               <li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                       role="button" aria-haspopup="true" aria-expanded="false">
                       <%= image_tag avatar_url(current_user), class: "img-circle avatar_small"%>    &nbsp;
                       <%= current_user.fullname %>    <span class="caret"></span>
                       </a>
              <ul class="dropdown-menu">  <%# for user only  %>
                <li><%= link_to "Dashboard", dashboard_path %></li>
                <li><%= link_to "List Your Space", new_room_path %></li>
                <li><%= link_to "Your Reservations", your_reservations_path %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
              </li>

            <% end %>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/rooms/#{params[:id]}")%>

    <nav class="navbar navbar-default" style="background-color: #565A5C">
      <div class="container">
        <ul class="nav navbar-nav">
          <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
          <li <% if current_page?(rooms_path) %> class="active" <% end %>><%= link_to "Manage Listings", rooms_path %></li>
          <li <% if current_page?(host_calendar_path) %> class="active" <% end %> ><%= link_to "Host Calendar", host_calendar_path %></li>
          </ul>
      </div>
    </nav>
<% end %>