config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
 resources :rooms, except: [:edit] do
  member do
    get 'listing'
    get 'pricing'
    get 'description'
    get 'amenities'
    get 'photo_upload'
    get 'location'
    get 'preload'
    get 'preview'
  end

  resources :photos, only: [:create, :destroy]
  resources :reservations, only: [:create]
  resources :calendars
 end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => 'reservations#approve'
      post '/decline' => 'reservations#decline'
    end
  end

    get '/host_calendar' => "calendars#host"

    get '/notification_settings' => 'settings#edit'
    post '/notification_settings' => 'settings#update'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  enum status: {Waiting: 0, Approved:1, Declined: 2}

  belongs_to :room
 belongs_to :user  #need to remove this line


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    #before_action :authenticate_user! # will need to remove this as guests will not be required
    # to create a user account or sign in
    before_action :set_reservation, only: [:approve, :decline]



    def create
      room = Room.find(params[:room_id])

      if current_user == room.user
        flash[:alert] = "You cannot book your own property!"
      else
        start_date = Date.parse(reservation_params[:start_date])
        end_date = Date.parse(reservation_params[:end_date])
        days = (end_date - start_date).to_i + 1


        @reservation = Reservation.new(reservation_params)
        # need to change this from current_user to guest
        @reservation.room = room
        @reservation.price = room.price
        @reservation.total = room.price * days

      #  @reservation.save

      if @reservation.save
        if room.Request?
          flash[:notice] = "Request sent successfully!"   # then send mailer with paypal request with total price
        else
          @reservation.Approved!
          flash[:notice] = "Reservation created successfully!" # then send mailer with paypal request with total price
        end
      else
        flash[:notice] = "Cannot make a reservation at this time!"
      end

      end
      redirect_to room
    end

    def your_trips
      @trips = current_user.reservations.order(start_date: :asc)
      #remove this route as guest will not be a user and not required to sign in. record
      #of trips will be sent via email
    end

    def your_reservations
      @rooms = current_user.rooms

    end

    def approve
    @reservation.Approved!
    redirect_to your_reservations_path
  end

  def decline
    @reservation.Declined!
    redirect_to your_reservations_path
  end

    private

      def set_reservation
        @reservation = Reservation.find(params[:id])
      end

      def reservation_params
        params.require(:reservation).permit(:start_date, :end_date, :guestname, :guestemail)
        # add guest name , email and phone number to permit?
      end
  end

app/views/reservations/_form.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

<div class="panel panel-default">
  <div class="panel-heading">
    <span><% if @room.Instant? %> <i class="fa fa-bolt" style="color: #ffb400"></i> <% end %>  $<%= @room.price %></span>
    <span class="pull-right">Per Night</span>
  </div>

  <div class="panel-body">
    <%= form_for([@room, @room.reservations.new]) do |f| %>
        <div class="row">
        <div class="col-md-6">
          <label>Check In</label>
          <%= f.text_field :start_date, readonly: true, placeholder: "Start Date", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
          <label>Check Out</label>
          <%= f.text_field :end_date, readonly: true, placeholder: "End Date", class: "form-control datepicker", disabled: true %>
        </div>
        <div class="col-md-6">
          <label>Guest Name</label>
          <%= f.text_field :guestname, placeholder: "Guest Name", class: "form-control" %>
        </div>
        <div class="col-md-6">
          <label>Guest Email</label>
          <%= f.text_field :guestemail, placeholder: "Guest Email", class: "form-control"%>
        </div>

        <%# need three fields here for guest : name, email and phone number. cannot hit submit unless these are filled out%>


    </div>

        <h4 class="message-alert text-center"><span id="message"></span></h4>
        <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>Price</td>
              <td class="text-right">$<%= @room.price %></td>
            </tr>
            <tr>
              <td>Night(s)</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">Total</td>
              <td class="text-right">$<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

        <br/>
        <% if @room.Instant? %>
            <%= f.submit "Book Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
        <% else %>
            <%= f.submit "Request Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
        <% end %>
        <%# cannot submit unless all fields are filled out in form %>

      <% end %>
      </div>
    </div>


    <script>

    function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
    }

    //new function>>>
      function resetUTC(d){
      var f = moment.utc(d);
      var now = new Date(f._d);
      var utcDate = new Date(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), now.getUTCHours(), now.getUTCMinutes(), now.getUTCSeconds());
      return utcDate;
      }

        $(function () {

         unavailableDates = [];

         $.ajax({
            url: '<%= preload_room_path(@room) %>',
            dateTyp: 'json',
            success: function(data) {

                $.each(data, function(arrID, arrValue) {
                    for(var d = resetUTC(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
                    unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
                    }
                });

             $('#reservation_start_date').datepicker({
                dateFormat: 'dd-mm-yy',
                minDate: 0,
                maxDate: '3m',
                beforeShowDay: checkDate,
                onSelect: function(selected) {
                    $('#reservation_end_date').datepicker("option", "minDate", selected);
                    $('#reservation_end_date').attr("disabled", false);

                 var start_date = $('#reservation_start_date').datepicker('getDate');
                var end_date = $('#reservation_end_date').datepicker('getDate');
                var nights = (end_date - start_date)/1000/60/60/24 + 1;

                var input = {
                'start_date': start_date,
                'end_date': end_date
                }


              $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @room.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);








                     }
                    }
                    });
                   }
                });

              $('#reservation_end_date').datepicker({
                dateFormat: 'dd-mm-yy',
                minDate: 0,
                maxDate: '3m',
                beforeShowDay: checkDate,
                onSelect: function(selected) {
                    $('#reservation_start_date').datepicker("option", "maxDate", selected);

                var start_date = $('#reservation_start_date').datepicker('getDate');
                var end_date = $('#reservation_end_date').datepicker('getDate');
                var nights = (end_date - start_date)/1000/60/60/24 + 1;

                var input = {
                'start_date': start_date,
                'end_date': end_date
                }

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @room.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });
          }
        });
      }
    });



  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link " %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>

    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Reservations
      </div>
      <div class="panel-body">

         <% @rooms.each do |room| %>
            <% room.reservations.each do |reservation| %>
                <div class="row">
                  <div class="col-md-2">
                    <%= reservation.start_date.strftime('%v') %>
                    <p> <%= reservation.status %> </p>
                    <div class="form-inline">
                      <% if reservation.Waiting? %>
                          <%= link_to approve_reservation_path(reservation), method: :post do %> <i class="fa fa-thumbs-up fa-lg"></i> <% end %> |
                          <%= link_to decline_reservation_path(reservation), method: :post do %> <i class="fa fa-thumbs-down fa-lg"></i> <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-md-2">
                    <%= link_to room_path(reservation.room) do %>
                        <%= image_tag reservation.room.cover_photo(:thumb) %>
                    <% end %>
                  </div>
                  <div class="col-md-5">
                    <%= link_to reservation.room.listing_name, room_path(reservation.room) %><br/><br/>
                    <span>
                <%#      <%= link_to user_path(reservation.user) do %>
                        <%#  <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                        <%= reservation.guestname %>
                        <%= reservation.guestemail %>
                    <%#  <% end %>
                    </span>
                  </div>
                </div>
                <hr/>

            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>